import {GoogleTagManager} from '@next/third-parties/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <body>{children}</body>
      <GoogleTagManager gtmId='G-JNZC27WEH5' />
    </html>
  );
}
